apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gator-dev

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/configmap.yaml
- ../../base/secrets.yaml
- ../../base/pvc.yaml
- ../../base/postgres.yaml
- ../../base/redis.yaml

patches:
- target:
    kind: Deployment
    name: gator-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"

- target:
    kind: ConfigMap
    name: gator-config
  patch: |-
    - op: replace
      path: /data/environment
      value: "development"
    - op: replace
      path: /data/log-level
      value: "DEBUG"

- target:
    kind: PersistentVolumeClaim
    name: gator-content-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "10Gi"

- target:
    kind: PersistentVolumeClaim
    name: gator-models-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "50Gi"

- target:
    kind: PersistentVolumeClaim
    name: postgres-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "10Gi"
